title: Postman COVID-19 API Resource Center
description: During the present novel coronavirus (COVID-19) pandemic, those on the front lines—including health care professionals, researchers, and government experts—need quick, easy access to real-time critical data. This type of information exchange is what APIs do best, and as an API-first company, Postman is committed to providing whatever assistance we can in this area.
image: https://postman-toolboxes2.s3.amazonaws.com/assets/covid-19.png
url: https://postman-toolboxes2.github.io/covid-19
email: covid-19@postman.com

github_user: postman-toolboxes2
github_repo: covid-19
github_branch: master

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
